services:
  docs:
    image: squidfunk/mkdocs-material
    ports:
      - "8000:8000"
    volumes:
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./docs:/docs/docs
    command: serve --dev-addr=0.0.0.0:8000 --livereload
