site_name: Fragments
site_url: https://python-fragments.io
repo_url: https://github.com/TheRunningAlgorithm2/python-fragments
repo_name: Python Fragments
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  custom_dir: docs/overrides
  palette:
    scheme: slate
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - extras.css

copyright: Developed and maintained by <a href="https://www.therunningalgorithm.com">TheRunningAlgorithm</a>

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.therunningalgorithm.com
      name: TheRunningAlgorithm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/the-running-algorithm
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/TheRunningAlgorithm2
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:matt@therunningalgorithm.info
      name: Contact

nav:
  - Introduction: index.md
  - Getting Started:
    - Checklist: getting-started/checklist.md
    - Installation: getting-started/installation.md
    - VS Code: getting-started/vs-code.md
    - LSP: getting-started/lsp.md
  - Syntax and Usage:
    - Fragments: syntax-and-usage/fragments.md
    - Interpolation: syntax-and-usage/interpolation.md
    - Attributes: syntax-and-usage/attributes.md
    - Control Flow: syntax-and-usage/control-flow.md
    - Components: syntax-and-usage/components.md
    - Comments: syntax-and-usage/comments.md
  - Transpiler:
    - 1. Transpilation: transpiler/transpilation.md
    - 2. HTML Library: transpiler/html-library.md
    - 3. Import Hook: transpiler/import-hook.md
  - Examples:
    - FastAPI: examples/fastapi.md
  - Benchmarks: benchmarks/index.md
