site_name: Python Fragments
repo_url: https://github.com/TheRunningAlgorithm2/python-fragments
repo_name: Python Fragments
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    scheme: slate
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - extras.css

nav:
  - Home: index.md
  - Transpiler: transpiler.md
  - Getting Started:
    - Installation: installation.md
    - IDE Tooling: ide-tooling.md
  - Syntax:
    - Fragments: syntax/fragments.md
    - Attributes: syntax/attributes.md
    - Control Flow: syntax/control-flow.md
    - Components: syntax/components.md
  - Examples:
    - FastAPI: examples/fastapi.md
